---
title: "Analysis of Instacart Dataset"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(flexdashboard)
```

```{r}
instacart <- read_csv("instacart_train_data.csv.zip")
```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart A
It shows that people generally place orders at noon and in the early afternoon. 

```{r}
# How many products are ordered in each hour of the day
instacart%>%
  filter(.,department =="produce")%>%
  group_by(order_hour_of_day)%>%
  summarize(number_of_order=n())%>%
  mutate(text_label = str_c("Hour:", order_hour_of_day, '\nNumber of order ', number_of_order)) %>% 
  plot_ly(x= ~order_hour_of_day, y=~number_of_order, text=~text_label,type="bar")
```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart B
It shows within the produce department, the order hour of the most 8 products are not significantly different.

```{r}
#check the distribution of order hour of the day for the most popular 8 products in produce department
popular_produce <- instacart%>%
  select(department, product_name)%>%
  filter(department =="produce")%>%
  group_by(product_name)%>%
  summarize(n=n())%>%
  arrange(desc(n))%>%
  top_n(8)%>%
  pull(product_name)


instacart%>%
  filter(product_name %in% popular_produce)%>%
  plot_ly(x= ~product_name, y=~order_hour_of_day,color= ~product_name, type = "box" )
 
```

### Chart C
It shows the distribution of orders over a week for 8 most populat department. The x-axis are ordered according to the overall number of orders.

```{r}
# check the distribution of orders in each day of week for the most populat 8 deparments
popular_department <- instacart%>%
  select(department)%>%
  group_by(department)%>%
  summarize(total=n())%>%
  arrange(desc(total))%>%
  top_n(8)%>%
  ungroup()

department <- instacart%>%
  select(department, order_dow)

data_popular_depart <-  inner_join(popular_department, department, by="department")%>%
  group_by(department, order_dow)%>%
  mutate(n=n())%>%
  distinct() %>% 
  ungroup()

data_popular_depart%>%
  mutate(department= fct_reorder(department,total))%>%
  plot_ly(x= ~department, y=~order_dow,z=~n, type = "heatmap" )

```

