---
title: "p8105_hw6_shiny_xz2678"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
  runtime: shiny
---


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(shiny)
instacart <- read_csv("../data/instacart_train_data.csv.zip")

#the selected department will be among the department which have the most order
popular_department <- instacart%>%
  select(department)%>%
  group_by(department)%>%
  summarize(total=n())%>%
  arrange(desc(total))%>%
  top_n(8)%>%
  ungroup()
```

```{r}
#selectinput widget
selectInput("department_choice", label = h3("Select department"),choices = popular_department, selected = "canned goods")

# sliderInput widget
sliderInput("time_choice", label = h3("Choose time range"), min =0,max = 24, step=1, round= True, value = c(8,17))

```

Row
-----------------------------------------------------------------------

### Chart A

```{r}
# show the number of order in selected time range and selected department
renderPlotly({ 
  instacart%>%
    filter(department == input$department_choice,
           order_hour_of_day %in% input$time_choice[1]:input$time_choice[2],
)%>%
    group_by(order_hour_of_day)%>%
    summarize(n=n())%>%
    plot_ly(x= ~order_hour_of_day, y=~n,  color=~order_hour_of_day,type="bar")  
  
})


```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Chart B

```{r}
# show distribution of order time of the most popular 8 products in selected department
renderPlotly({
  popular_produce <- instacart%>%
    select(department, product_name)%>%
    filter(department == input$department_choice)%>%
    group_by(product_name)%>%
    summarize(n=n())%>%
    arrange(desc(n))%>%
    top_n(8)%>%
    ungroup()

produce <- instacart%>%
  select(department, product_name,order_hour_of_day)%>%
  filter(department == input$department_choice)
  
data_popular_produce <-  inner_join(popular_produce, produce, by="product_name")

data_popular_produce%>%
  arrange(n)%>%
  plot_ly(x= ~product_name, y=~order_hour_of_day,color= ~product_name, type = "box" )
})
```

### Chart C

```{r}
#show the number of order in each day of week in select department(and 8 least popolar department) and selected time range
renderPlotly({
  unpopular_department <- instacart%>%
    select(department)%>%
    group_by(department)%>%
    summarize(total=n())%>%
    arrange(desc(total))%>%
    top_n(-8)%>%
    pull(department)
  
  show_department <- c(unpopular_department,input$department_choice)
  
  data_show_department <- instacart%>%
    select(department,order_hour_of_day,order_dow)%>%
    filter(department == show_department)%>%
    group_by(department)%>%
    mutate(total=n())%>%
    ungroup()
  
  data_show_department%>%
    filter(order_hour_of_day %in% input$time_choice[1]:input$time_choice[2])%>%
    group_by(department, order_dow)%>%
    mutate(n=n())%>%
    ungroup()%>%
    mutate(department= fct_reorder(department,total))%>%
    plot_ly(x= ~department, y=~order_dow,z=~n, type = "heatmap")
})
```

